name: Continuous Integration

on:
  push:
    branches: [master, develop, v1/develop, feat/nexus]
  pull_request:
    branches: [master, develop, v1/develop, feat/nexus]

jobs:
  # code-style:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - name: install
  #       run: npm install
  #     - name: eslint
  #       run: npm run lint

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #     - name: install
  #       run: npm install

  build:
    # needs: [code-style, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install
        run: npm install
      - name: build app
        run: npm run build
      - name: build artifact
        uses: actions/upload-artifact@v2
        with:
          name: vue-app-dist
          path: |
            dist
            !dist/**/*.md
          retention-days: 5
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: vue-app-dist
      - name: compress folder
        run: tar -zcvf vue-app.tar.gz dist/
      - name: Nexus Repository Publisher for GitHub Actions
        uses: sonatype-nexus-community/nexus-repo-github-action@1.0.0
        with:
          serverUrl: http://nexus.romainbdt.fr:8081
          username: admin
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: raw
          repository: preudhomme-repo
          filename: vue-app.tar.gz
          coordinates: artifactId=app version=1.0.0
          assets: extension=tar.gz



  documentations:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: install
        run: npm install
      - name: build documentation
        run: npm run doc

  release:
    needs: [ documentations ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      # - name: build release
      #  run: npm run changelog-git


