name: Continuous Integration

on:
  push:
    branches: [master, develop, v1/develop]
  pull_request:
    branches: [master, develop, v1/develop]

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node_version: 12
      - name: install
        run: npm install
      - name: eslint
        run: npm run lint

build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node_version: 12
    - name: install
      run: npm install
    - name: build app
      run: npm run build

test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node_version: 12
    - name: install
      run: npm install
